# Generated by Django 5.2.16 on 2026-09-25 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctororganization'),
        ('patients', '0002_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(max_length=255)),
                ('history_type', models.CharField(choices=[('CHRONIC_CONDITION', 'Chronic Condition'), ('ACUTE_ILLNESS', 'Acute Illness'), ('SURGERY', 'Surgery'), ('INJURY', 'Injury'), ('HOSPITALIZATION', 'Hospitalization'), ('OTHER', 'Other')], max_length=30)),
                ('diagnosed_on', models.DateField(blank=True, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('IN_REMISSION', 'In Remission'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_medical_histories', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-diagnosed_on', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='medical_rec_patient_be765b_idx'), models.Index(fields=['patient', 'history_type'], name='medical_rec_patient_aa82b5_idx')],
            },
        ),
    ]
