# Generated by Django 5.2.16 on 2026-09-26 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctororganization'),
        ('medical_records', '0002_alter_medicalhistory_patient'),
        ('patients', '0002_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', models.CharField(max_length=255)),
                ('allergy_type', models.CharField(choices=[('DRUG', 'Drug'), ('FOOD', 'Food'), ('ENVIRONMENTAL', 'Environmental'), ('CONTACT', 'Contact'), ('OTHER', 'Other')], max_length=20)),
                ('reaction', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('LIFE_THREATENING', 'Life Threatening'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergies', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_allergies', to='doctors.doctor')),
            ],
            options={
                'ordering': ['allergen'],
                'indexes': [models.Index(fields=['patient', 'status'], name='medical_rec_patient_fa13b8_idx'), models.Index(fields=['patient', 'allergy_type'], name='medical_rec_patient_a8a454_idx')],
            },
        ),
    ]
