# Generated by Django 5.2.16 on 2026-09-28 10:04

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(max_length=255)),
                ('diagnosis_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('PROVISIONAL', 'Provisional')], max_length=20)),
                ('diagnosed_on', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-diagnosed_on', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('diagnosis_type', 'PRIMARY')), fields=('consultation',), name='unique_primary_diagnosis_per_consultation')],
            },
        ),
    ]
