# Generated by Django 5.2.16 on 2026-09-28 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_type', models.CharField(choices=[('MEDICATION', 'Medication'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('PROCEDURE', 'Procedure'), ('SURGERY', 'Surgery'), ('LIFESTYLE', 'Lifestyle'), ('DIET', 'Diet'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='PLANNED', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='consultations.consultation')),
                ('diagnoses', models.ManyToManyField(blank=True, related_name='treatments', to='treatments.diagnosis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
