# Generated by Django 5.2.16 on 2026-09-28 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='treatments.treatment')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
