# Generated by Django 5.2.16 on 2026-09-19 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('master', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joined_on', models.DateField()),
                ('left_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_organizations', to='master.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_assignments', to='doctors.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'doctor__user__first_name'],
                'indexes': [models.Index(fields=['doctor', 'organization'], name='doctors_doc_doctor__b5ec71_idx'), models.Index(fields=['organization', 'department'], name='doctors_doc_organiz_122c84_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'organization', 'department'), name='unique_doctor_organization_department')],
            },
        ),
    ]
